### ISSUE TITLE
Could this also work with inbox?

### ISSUE THREAD

**Issue by cpaulik** [Malabarba/gmail-mode#3]
I've tried adding 

```elisp
  (eval-after-load 'edit-server
    '(add-to-list 'edit-server-url-major-mode-alist
                  '("inbox\\.google\\." . gmail-message-edit-server-mode))) 
```
which seemed to work fine but I'm not sure if this is all that has to be changed

**Comment by Malabarba** [comment]
If it works for you I'm happy to add it in. I'll probably test it myself when I have time.
Let me know if inbox behaves differently in any way.

**Comment by vrih** [comment]
Have added that to my emacs config and it seems to work well with inbox.

**Comment by Malabarba** [comment]
Thanks for reminding me!
Just added this to version 1.4.
