### ISSUE TITLE
Markdown/Ham-Mode markup stripped when returning from Emacs to Gmail/Inbox

### ISSUE THREAD

**Issue by jonathanwilner** [Malabarba/gmail-mode#5]
Hi, I've used gmail-mode successfully for quite some time - it's a lifesaver. Recently, either something with Emacs or my configuration (or Gmail/Inbox) changed & I am not able to properly pass back _Markdown_ (tried to do italics there!) formatted text back from emacs and have it preserved in Chrome text fields. The result is not just missing bullets, but even line breaks. Can you advise as to something I've done wrong in my config or skipped a step that causes things to not work between Chrome and Emacs?

**Comment by Malabarba** [comment]
Nowadays, I can't even manage to use edit-with-emacs in Gmail anymore, so I guess I can close this with a sad face. :(
